services:
  supplier_app:
    build: .
    container_name: supplier_app
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    networks:
      - labo03-network

networks:
  labo03-network:
    driver: bridge
    external: true
